### ISSUE TITLE
Microsoft Store link doesn't work

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [TheNewJavaman/unreal-vr#29]
Microsoft Store link (https://www.microsoft.com/store/apps/9PJBS037PW38) on https://unrealvr.dev website doesn't work:

> We are sorry, the page you requested cannot be found. The URL may be misspelled or the page you're looking for is no longer available.

**Comment by TheNewJavaman** [comment]
Thanks for reporting this @FluorescentHallucinogen. There are no official releases yet, so Microsoft hasn't created a landing page for the app. This should be fixed within the next month, when the beta comes out. In the meantime, I'll disable the link and add a message about how it's still a WIP.

**Comment by FluorescentHallucinogen** [comment]
@TheNewJavaman Where can I download nightly (alpha) builds? Do you plan to publish compiled binaries [here](https://github.com/TheNewJavaman/unreal-vr/releases)?

**Comment by TheNewJavaman** [comment]
@FluorescentHallucinogen I will restrict nightly builds to Patrons ([patreon.com/gpizarro](https://www.patreon.com/gpizarro)), but the source code will always be available if you want to build it yourself.
