### ISSUE TITLE
Geometric 3D

### ISSUE THREAD

**Issue by VR-Punk** [TheNewJavaman/unreal-vr#44]
Does your Project support alternate eye rendering 3D, which is geometric too, or full geometric 3D ? Because almost all upcoming Triple A Blockbuster will need a RTX 4080 with a price over 2000 - 2500 $ and with 300% more performance than a RTX 3080 to play in full geometric 3D ? In my opinion the best choice would be to support both, alternate eye rendering 3D and full geometric 3D ! What do you think about that ?

**Comment by TheNewJavaman** [comment]
This project only supports geometric 3D rendering, and will only support G3D for the foreseeable future. It uses alternate eye rendering, and does AER very well -- there is no artifacting, no ghosting, and no nausea. By full G3D, I assume you mean synchronous rendering, which is planned to be implemented later. Synchronous rendering is **not easy** to mod in. Don't take it as a given.

Don't be too concerned about needing expensive GPUs to play AAA games in VR. You're overestimating the computational work required for each frame. On my RTX 3070 Ti, I can play Ghostrunner at 4000x2000 resolution at 140 FPS on my Oculus Quest 2. *However*, this is only using ~65% of my GPU! I am still optimizing the mod, so it is feasible that with more work, you could play AAA games on a Quest 2 at 2k90hz, using a mid-range GPU! On lower-end hardware, you might need to scale back the resolution, but it'll still look fine.

**Comment by VR-Punk** [comment]
I have a RTX 3080 Ti and can play Days Gone (DX11+UE4) in 1440p only in vorpx G3D ! I think the Geometric 3D, which is used in the Cyberpunk 2077 mods is a better choice. (I didn't understand your first paragraph, sorry)
