### ISSUE TITLE
G3D support

### ISSUE THREAD

**Issue by VR-Punk** [TheNewJavaman/unreal-vr#45]
I have a RTX 3080 Ti and can play Days Gone (DX11+UE4) in 1440p only in vorpx G3D ! In my opinion the Geometric 3D, which is used in the Cyberpunk 2077 mods is a better choice for your Project !

**Comment by VR-Punk** [comment]
In Jedi Fallen Order (DX11+UE4) I can play in 2560x1920 only in vorpx G3D !

**Comment by TheNewJavaman** [comment]
As I said in #44, this project uses G3D.
